<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Article', 'doctrine');

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property clob $content
 * @property string $image_path
 * @property integer $status
 * @property integer $group_id
 * @property string $meta_title
 * @property string $meta_keyword
 * @property string $meta_description
 * @property ArticleGroup $ArticleGroup
 * 
 * @method string       getTitle()            Returns the current record's "title" value
 * @method clob         getDescription()      Returns the current record's "description" value
 * @method clob         getContent()          Returns the current record's "content" value
 * @method string       getImagePath()        Returns the current record's "image_path" value
 * @method integer      getStatus()           Returns the current record's "status" value
 * @method integer      getGroupId()          Returns the current record's "group_id" value
 * @method string       getMetaTitle()        Returns the current record's "meta_title" value
 * @method string       getMetaKeyword()      Returns the current record's "meta_keyword" value
 * @method string       getMetaDescription()  Returns the current record's "meta_description" value
 * @method ArticleGroup getArticleGroup()     Returns the current record's "ArticleGroup" value
 * @method Article      setTitle()            Sets the current record's "title" value
 * @method Article      setDescription()      Sets the current record's "description" value
 * @method Article      setContent()          Sets the current record's "content" value
 * @method Article      setImagePath()        Sets the current record's "image_path" value
 * @method Article      setStatus()           Sets the current record's "status" value
 * @method Article      setGroupId()          Sets the current record's "group_id" value
 * @method Article      setMetaTitle()        Sets the current record's "meta_title" value
 * @method Article      setMetaKeyword()      Sets the current record's "meta_keyword" value
 * @method Article      setMetaDescription()  Sets the current record's "meta_description" value
 * @method Article      setArticleGroup()     Sets the current record's "ArticleGroup" value
 * 
 * @package    source
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tieu de bai viet',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'comment' => 'Mô tả ngắn',
             ));
        $this->hasColumn('content', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'ckeditor',
             'notnull' => true,
             'comment' => 'Noi dung bai viet',
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'duong dan anh minh hoa bai viet',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'comment' => '0: khong hien thi, 1: hien thi',
             'length' => 1,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'id nhom tuong ung cua bai viet',
             ));
        $this->hasColumn('meta_title', 'string', 255, array(
             'type' => 'string',
             'comment' => 'meta title',
             'length' => 255,
             ));
        $this->hasColumn('meta_keyword', 'string', 255, array(
             'type' => 'string',
             'comment' => 'meta keyword',
             'length' => 255,
             ));
        $this->hasColumn('meta_description', 'string', 255, array(
             'type' => 'string',
             'comment' => 'meta description',
             'length' => 255,
             ));


        $this->index('article_id_index', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
        $this->option('comment', 'Bang luu thong tin bai viet');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ArticleGroup', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'uniqueBy' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             'builder' => 
             array(
              0 => 'removeSignClass',
              1 => 'removeSign',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}