<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProductCategory', 'doctrine');

/**
 * BaseProductCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $category_id
 * @property Product $Product
 * @property Category $Category
 * 
 * @method integer         getProductId()   Returns the current record's "product_id" value
 * @method integer         getCategoryId()  Returns the current record's "category_id" value
 * @method Product         getProduct()     Returns the current record's "Product" value
 * @method Category        getCategory()    Returns the current record's "Category" value
 * @method ProductCategory setProductId()   Sets the current record's "product_id" value
 * @method ProductCategory setCategoryId()  Sets the current record's "category_id" value
 * @method ProductCategory setProduct()     Sets the current record's "Product" value
 * @method ProductCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    source
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_category');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Ten nha mang',
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Mo ta',
             ));

        $this->option('comment', 'Bang luu thong tin san pham thuoc danh muc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}