# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_DEPRECATED)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            fe647bd9638cead6d4ff216665752891a34ff27a

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    enabled_modules:        [default, tmcTwitterBootstrap, sfGuardAuth, sfGuardUser, sfFormExtraPlugin, sfCaptchaGD]
    standard_helpers:       [Partial, Cache, I18N]
    i18n:                   true
    charset: utf-8
    default_culture: vi
  .actions:
    login_module:           sfGuardAuth
    login_action:           signin
    error_404_module: default
    error_404_action: error404
