# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    
    - <?php echo sfConfig::get("app_domain_web_root")?>/css/main.css
    - <?php echo sfConfig::get("app_domain_web_root")?>/css/admin/filters.css
    - <?php echo sfConfig::get("app_domain_web_root")?>/css/admin/coder_update.css?v=1
    - <?php echo sfConfig::get("app_domain_web_root")?>/css/jquery-ui-1.8.22.custom.css

  javascripts:    
    - <?php echo sfConfig::get("app_domain_web_root")?>/js/jquery-ui-1.8.22.custom.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/js/admin/vtBackend.js

  has_layout:     true
  layout:         layout
