<?php

/**
 * ArticleGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    source
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ArticleGroup extends BaseArticleGroup
{
  public function getListPositionName(){
    $positionArr = ArticleGroupPosition::getArr();
    if($this->getPosition()){
      $posNameArr = array();
      $curPositionArr = explode(',',$this->getPosition());
      foreach($curPositionArr as $position){
        $posNameArr[] = $positionArr[$position];
      }
      return implode(',',$posNameArr);
    }
    return '';
  }
}