<?php

/**
 * Banner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    source
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banner extends BaseBanner
{
    public function getStatusName(){
        $statusArr = array(0 => 'Không hiển thị', 1 => 'Hiển thị');
        return isset($statusArr[$this->getStatus()]) ? $statusArr[$this->getStatus()] : '';
      }
}