<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    public static function getListActiveCategory($limit = null){
      $query = self::getInstance()->createQuery('c')
        ->innerJoin('c.ProductCategory pc')
        ->where('c.is_active = 1')
        ->orderBy('priority');
      if($limit)
        $query->limit($limit);
      return $query->fetchArray();
    }

    public static function getCategoryBySlug($slug){
      return self::getInstance()->createQuery()
        ->where('is_active = 1')
        ->andWhere('slug = ?', $slug)
        ->fetchOne();
    }
}