<?php

/**
 * DetailOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetailOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetailOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetailOrder');
    }

    public static function saveOrder($orderId, $productId, $productName, $price, $quantity){
        try{
            $order = new DetailOrder();
            $order->setOrderId($orderId);
            $order->setProductId($productId);
            $order->setProductName($productName);
            $order->setPrice($price);
            $order->setQuantity($quantity);
            $order->save();
        }catch(Exception $e){

        }
    }
}