<?php

/**
 * DetailOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetailOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetailOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetailOrder');
    }
}