<?php

/**
 * ProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductCategory');
    }

    public static function getListCategoryByProduct($productId){
      return self::getInstance()->createQuery()
        ->select('category_id')
        ->where('product_id = ?', $productId)
        ->execute(array(), Doctrine::HYDRATE_ARRAY_SHALLOW);
    }
}