<?php

/**
 * VtUserSigninLockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VtUserSigninLockTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VtUserSigninLockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VtUserSigninLock');
    }
}