# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
#    charset: utf-8
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/bootstrap.min.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/font-awesome.min.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/bootstrap-grid.min.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/bootstrap-reboot.min.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/font-techmarket.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/slick.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/techmarket-font-awesome.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/slick-style.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/animate.min.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/style.css?v=1: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/colors/red.css: { media: all }
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/css/roboto.css: { media: all }

  javascripts:
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/jquery.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/tether.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/bootstrap.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/jquery-migrate.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/hidemaxlistitem.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/jquery-ui.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/hidemaxlistitem.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/jquery.easing.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/scrollup.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/jquery.waypoints.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/waypoints-sticky.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/pace.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/slick.min.js
    - <?php echo sfConfig::get("app_domain_web_root")?>/assets/js/scripts.js

  has_layout:     true
  layout:         layout
