all:
  pattern_password: '/^\S*(?=\S{8,})(?=\S*\d)(?=\S*\W+)(?![.\n])(?=\S*[a-zA-Z])\S*$/'
  pattern_username: '/^([a-zA-Z])+([a-zA-Z0-9_]){5,29}$/'
  ckfinder:
    active: true
    basePath: '/js/ckfinder/'
  ckeditor:
    active: true
    basePath: '/js/ckeditor/'
  default_meta_title: 'Cờ bạc bịp'
  phone_number: "0354926551";
  domain_web_root: "http://localhost:8083"
