<?php
/**
 * Created by JetBrains PhpStorm.
 * User: tuanbm
 * Date: 9/10/12
 * Time: 5:17 PM
 * To change this template use File | Settings | File Templates.
 */

class sfResizedImage extends sfValidatedFileViettel
{

  /**
   * Saves the uploaded file.
   *
   * This method can throw exceptions if there is a problem when saving the file.
   *
   * If you don't pass a file name, it will be generated by the generateFilename method.
   * This will only work if you have passed a path when initializing this instance.
   *
   * @param  string $file      The file path to save the file
   * @param  int    $fileMode  The octal mode to use for the new file
   * @param  bool   $create    Indicates that we should make the directory before moving the file
   * @param  int    $dirMode   The octal mode to use when creating the directory
   *
   * @return string The filename without the $this->path prefix
   *
   * @throws Exception
   */
//  public static function generateFolder()
//  {
//    $dayFolder = sfConfig::get('sf_web_dir') . '/frame_images/' . date('Y') . '/' . date('m') . '/' . date('d');
//
//    if (!is_dir($dayFolder)) {
//      @mkdir($dayFolder, 0777)
//    }
//    return
//  }

  public function save($file = null, $fileMode = 0666, $create = true, $dirMode = 0777)
  {
    $saved = parent::save($file, $fileMode, $create, $dirMode);
    $this->createThumbnailImage("thumbnail",150,150);
    return $saved;
  }

}